# Generated by Django 5.0.7 on 2024-10-01 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinnacle_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='application_name',
        ),
    ]
