# Generated by Django 5.0.7 on 2024-10-01 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinnacle_app', '0002_remove_application_application_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentlabel',
            name='finance_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
