# Generated by Django 5.0.7 on 2024-10-01 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinnacle_app', '0004_alter_referral_referee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basiccontactinformation',
            name='phone_number',
            field=models.CharField(max_length=11),
        ),
    ]
