# Generated by Django 5.0.7 on 2024-10-02 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pinnacle_app', '0006_remove_financialinformation_types_of_collateral'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='documentupload',
            unique_together={('application', 'file', 'label')},
        ),
    ]
