# Generated by Django 5.0.7 on 2024-10-02 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinnacle_app', '0007_alter_documentupload_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationstatus',
            name='status',
            field=models.CharField(choices=[('submitted', 'Submitted'), ('in_progress', 'In Progress'), ('under_review', 'Under Review'), ('completed', 'Completed'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='in_progress', max_length=20),
        ),
    ]
