# Generated by Django 5.0.7 on 2024-10-05 21:27

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinnacle_app', '0009_alter_basiccontactinformation_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='referee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referred_by', to='pinnacle_app.user'),
        ),
        migrations.AlterField(
            model_name='referral',
            name='referrer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='pinnacle_app.user'),
        ),
        migrations.CreateModel(
            name='ReferralInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referee_email', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('Invitation_Sent', 'Invitation Sent'), ('Invitation_Accepted', 'Invitation Accepted'), ('Application_Completed', 'Application Completed'), ('Application_Rejected', 'Application Rejected')], default='Invitation_Sent', max_length=30)),
                ('date_sent', models.DateTimeField(auto_now_add=True)),
                ('date_accepted', models.DateTimeField(blank=True, null=True)),
                ('date_completed', models.DateTimeField(blank=True, null=True)),
                ('date_rejected', models.DateTimeField(blank=True, null=True)),
                ('referral_reward_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('earned_from_referral', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('referee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals_received', to='pinnacle_app.user')),
                ('referrer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to='pinnacle_app.user')),
            ],
        ),
    ]
