# Generated by Django 5.0.7 on 2024-10-08 19:12

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinnacle_app', '0012_alter_referral_referee_alter_referral_referrer'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='funding_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
