# Generated by Django 5.0.7 on 2024-11-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinnacle_app', '0016_alter_financialinformation_annual_revenue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentupload',
            name='file',
            field=models.URLField(blank=True, null=True),
        ),
    ]
