# Generated by Django 5.0.7 on 2024-11-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinnacle_app', '0017_alter_documentupload_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentupload',
            name='file',
            field=models.CharField(default='', max_length=255),
        ),
    ]
