# Generated by Django 5.0.7 on 2024-11-24 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinnacle_app', '0020_rename_is_staff_user_is_admin_user_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_superAdmin',
            field=models.BooleanField(default=False),
        ),
    ]
