# Generated by Django 5.0.7 on 2024-11-26 08:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinnacle_app', '0022_user_admin_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_location',
            field=models.CharField(default='N/A', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_login',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
