# Generated by Django 5.0.7 on 2024-11-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinnacle_app', '0024_alter_user_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_location_ip',
            field=models.CharField(default='N/A', max_length=255, null=True),
        ),
    ]
