# Generated by Django 5.0.7 on 2024-12-26 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinnacle_app', '0025_user_last_location_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='basiccontactinformation',
            name='home_address',
            field=models.CharField(default='ABC Street', max_length=255),
        ),
        migrations.AddField(
            model_name='basiccontactinformation',
            name='is_homeOwner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='basiccontactinformation',
            name='is_tenant',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='basiccontactinformation',
            name='other',
            field=models.BooleanField(default=False),
        ),
    ]
