# Generated by Django 5.0.7 on 2024-12-26 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinnacle_app', '0026_basiccontactinformation_home_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basiccontactinformation',
            name='is_homeOwner',
        ),
        migrations.RemoveField(
            model_name='basiccontactinformation',
            name='is_tenant',
        ),
        migrations.RemoveField(
            model_name='basiccontactinformation',
            name='other',
        ),
        migrations.AddField(
            model_name='basiccontactinformation',
            name='if_other',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='basiccontactinformation',
            name='resident_type',
            field=models.CharField(choices=[('home_owner', 'Home Owner'), ('tenant', 'Tenant'), ('other', 'Other')], default='home_owner', max_length=255),
        ),
    ]
