# Generated by Django 5.0.7 on 2025-03-13 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pinnacle_app', '0027_remove_basiccontactinformation_is_homeowner_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminEmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_to', models.EmailField(max_length=254)),
                ('email_by', models.CharField(max_length=255)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Sent', 'Invitation Sent'), ('Accepted', 'Accepted')], default='Sent', max_length=10)),
            ],
        ),
    ]
